### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by Powerful845tiger** [doookkie/auternos#3]
How do I run it on replit
It keeps on telling this 
How should I make it executable  
os.system("killall chromium")
os.system("killall chromium")

os.system("killall chromium")
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auternos.py", line 6, in <module>
    driver = webdriver.Chrome('/path/to/bin/chromedriver')
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by hipeopeo** [comment]
chromedriver is not literally located in '/path/to/bin/chromedriver'.

From further research, relpit does not appear to have a way of running chromedriver either (https://www.reddit.com/r/learnpython/comments/a58z9w/using_chromedriver_in_replit_python/).

I believe this is where a PhantomJS implementation in the code would be best so I'll look into that if I can.
