### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by UndevDRGN** [doookkie/auternos#6]
C:\Users\Administrator\Desktop\auternos-master\auternos.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=r'C:\Users\Administrator\Desktop\auternos-master\chromedriver_win32\chromedriver')

DevTools listening on ws://127.0.0.1:53187/devtools/browser/373ee8c8-a4a7-4005-bfdf-9c2791c2959e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\auternos-master\auternos.py", line 12, in <module>
    driver = webdriver.Chrome(options=options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

[6392:4360:1214/174122.816:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[6392:4848:1214/174122.816:ERROR:device_event_log_impl.cc(214)] [17:41:22.826] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[6392:4360:1214/174122.816:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[6392:4360:1214/174122.831:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[6392:4848:1214/174122.831:ERROR:device_event_log_impl.cc(214)] [17:41:22.841] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
[6392:4360:1214/174122.863:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.
[6392:4848:1214/174122.921:ERROR:device_event_log_impl.cc(214)] [17:41:22.922] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

**Comment by ddomino007** [comment]
Your chromedriver executable isn't in path. It's clearly what it reports in the error.
